export const constants = {
  MONGO_URI: 'MONGO_URI',
  ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
  EMAIL_FROM: 'EMAIL_FROM',
  EMAIL_FROM_PASSWORD: 'EMAIL_FROM_PASSWORD',
  JWT_SECRET: 'JWT_SECRET',
  REFRESH_TOKEN_EXPIRES_IN: 'REFRESH_TOKEN_EXPIRES_IN',
  APP_URI: 'https://nestjs-homework-api.herokuapp.com/api',
};
